### ISSUE TITLE
paginate trending

### ISSUE THREAD

**Issue by AlexVCS** [Mango-Entertainment/mango-entertainment#69]
may need to add more data before making the change, but paginate the trending section in lieu of the side scroll

**Comment by ssmodish** [comment]
Or a carousel

**Comment by ssmodish** [comment]
Trending based on overall and/or recent bookmarks for each title maybe?
We'll have to read those things the other team shared to get ideas.

**Comment by ssmodish** [comment]
Carousel makes this path obsolete.
